# pH Recognition using RGB Color 

In [1]:
#importing the packages.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [2]:
#reading the dataset.
ds = pd.read_csv('../dataset/ph-data.csv')
ds.head()

blue  green  red  label
0    36     27  231      0
1    36     84  250      1
2    37    164  255      2
3    22    205  255      3
4    38    223  221      4

In [3]:
#dataset is consistent. 
ds.label.value_counts()

14    44
12    44
11    44
10    44
9     44
8     44
7     44
6     44
5     44
4     44
3     44
2     44
1     44
13    43
0     38
Name: label, dtype: int64

In [4]:
#selecting X and y for classification.
X = ds.iloc[:, :-1].values
y = ds.iloc[:, -1].values

In [5]:
print(X)

[[ 36  27 231]
 [ 36  84 250]
 [ 37 164 255]
 ...
 [169  62  48]
 [173  37  79]
 [131   2  77]]


In [6]:
#reshaping y for regression.
y = y.reshape(len(y),1)
print(y)

[[ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2]
 [ 3]
 [ 4]
 [ 5]
 [ 6]
 [ 7]
 [ 8]
 [ 9]
 [10]
 [11]
 [12]
 [13]
 [14]
 [ 0]
 [ 1]
 [ 2

In [7]:
#scaling the independent and dependent variable.
from sklearn.preprocessing import StandardScaler
sc_X = StandardScaler()
sc_y = StandardScaler()
X = sc_X.fit_transform(X)
y = sc_y.fit_transform(y)

In [8]:
print(X)

[[-0.71132942 -1.42334289  1.23272598]
 [-0.71132942 -0.63639311  1.44498649]
 [-0.69798139  0.46809779  1.50084452]
 ...
 [ 1.06395863 -0.94012811 -0.8116779 ]
 [ 1.11735075 -1.28528152 -0.46535812]
 [ 0.55673347 -1.7684963  -0.48770133]]


In [9]:
print(y)

[[-1.64659949]
 [-1.41320911]
 [-1.17981874]
 [-0.94642836]
 [-0.71303798]
 [-0.47964761]
 [-0.24625723]
 [-0.01286685]
 [ 0.22052353]
 [ 0.4539139 ]
 [ 0.68730428]
 [ 0.92069466]
 [ 1.15408504]
 [ 1.38747541]
 [ 1.62086579]
 [-1.64659949]
 [-1.41320911]
 [-1.17981874]
 [-0.94642836]
 [-0.71303798]
 [-0.47964761]
 [-0.24625723]
 [-0.01286685]
 [ 0.22052353]
 [ 0.4539139 ]
 [ 0.68730428]
 [ 0.92069466]
 [ 1.15408504]
 [ 1.38747541]
 [ 1.62086579]
 [-1.64659949]
 [-1.41320911]
 [-1.17981874]
 [-0.94642836]
 [-0.71303798]
 [-0.47964761]
 [-0.24625723]
 [-0.01286685]
 [ 0.22052353]
 [ 0.4539139 ]
 [ 0.68730428]
 [ 0.92069466]
 [ 1.15408504]
 [ 1.38747541]
 [ 1.62086579]
 [-1.64659949]
 [-1.41320911]
 [-1.17981874]
 [-0.94642836]
 [-0.71303798]
 [-0.47964761]
 [-0.24625723]
 [-0.01286685]
 [ 0.22052353]
 [ 0.4539139 ]
 [ 0.68730428]
 [ 0.92069466]
 [ 1.15408504]
 [ 1.38747541]
 [ 1.62086579]
 [-1.64659949]
 [-1.41320911]
 [-1.17981874]
 [-0.94642836]
 [-0.71303798]
 [-0.47964761]
 [-0.24625

In [10]:
#splitting the dataset into test and training.
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 1)

In [11]:
#importing the packages.
from sklearn.linear_model import LinearRegression
from sklearn.ensemble import RandomForestRegressor
from sklearn.tree import DecisionTreeRegressor
from sklearn.svm import SVR
from sklearn.linear_model import Ridge
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score

SEED = 1

#variable initiation.
rf = RandomForestRegressor(random_state = SEED)
dt = DecisionTreeRegressor(random_state = 0)
svr = SVR(kernel = 'rbf')
ridge = Ridge(alpha=0.1, normalize=True)
lr = LinearRegression()

#storing in an array.
regressors = [('Multiple Linear Regression', lr),
              ('Ridge Regression', ridge),
              ('SVR', svr),
              ('Decision Tree', dt),
              ('Random Forest', rf)]

In [12]:
for reg_name, reg in regressors:
    
    #fit the model.
    reg.fit(X_train, y_train)
    
    #predicting test set results.
    y_pred = reg.predict(X_test)
    
    #reshaping into former form.
    np.set_printoptions(precision=2)
    np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1)
    
    #printing r2_score.
    print('{:s} : {:f}'.format(reg_name, r2_score(y_test, y_pred)))

Multiple Linear Regression : 0.682162
Ridge Regression : 0.682794
SVR : 0.934827
Decision Tree : 0.946644
Random Forest : 0.952970

C:\Users\gargy\anaconda3\lib\site-packages\sklearn\utils\validation.py:760: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
C:\Users\gargy\AppData\Roaming\Python\Python37\site-packages\ipykernel_launcher.py:4: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  after removing the cwd from sys.path.


In [13]:
from sklearn.externals import joblib
joblib.dump(lr, 'model.pkl')

C:\Users\gargy\anaconda3\lib\site-packages\sklearn\externals\joblib\__init__.py:15: FutureWarning: sklearn.externals.joblib is deprecated in 0.21 and will be removed in 0.23. Please import this functionality directly from joblib, which can be installed with: pip install joblib. If this warning is raised when loading pickled models, you may need to re-serialize those models with scikit-learn 0.21+.
  warnings.warn(msg, category=FutureWarning)


['model.pkl']